<?php 
	
	//test2
	
	/*
	if(isset($_POST['a']) and isset($_POST['b'])) {
		$a = $_POST['a'];
		$b = $_POST['b'];
		$c = $a + $b;
		
		if($c == 3) {
			echo $a.' + '.$b.' = '.$c;
		} else {
			echo $a.' + '.$b.' = '.$c;
		}
	}*/
	
	//test3
	
	/*function tintin($a) {
		$c = array();
		foreach ($a as $b) {
			$c[] = $a[$b];
		}
		return $c;
	}

	$d = array(5,3,4,1,0,2);
	$s = tintin($d);
	
	echo "<pre>";
	print_r($s);
	echo "</pre>";*/
	

	//test3
	
	/*function milou($a) {
		return array_reverse($a);
	}

	$d = array(5,3,4,1,0,2);
	$s = milou($d);
	$l = array_flip($s);
	
	echo "<pre>";
	print_r($s);
	print_r($l);
	echo "</pre>";*/
	
	//test5
	/*function milou($a) {
		$c = array();
		foreach ($a as $b => $d) {
			if($b % 2 == 0) {
				array_unshift($c,$d);
			}
		}
		return $c;
	}

	$d = array(5,3,4,1,0,2);
	$s = milou($d); // [0,4,5]
	echo "<pre>";
	print_r($s);
	echo "</pre>";*/
	/*session_start();
	
	if(isset($_POST['age1'], $_POST['age2'], $_POST['age3'])) {
		if(!empty($_POST['age1']) and !empty($_POST['age2']) and !empty($_POST['age2'])) {
			$age = array();
			$age[] = $_POST['age1'];
			$age[] = $_POST['age2'];
			$age[] = $_POST['age3'];
			$s = 0;
			foreach($age as $a)
			{
				$s += $a;
			}
			$_SESSION['ageMoyen'] = $s / count($age);
		}
	}*/
	/*
	if(isset($_GET['mdp']) and !empty($_GET['mdp'])) {
		$mdp = $_GET['mdp'];
		if(preg_match('#^[a-zA-Z]{8,}$#',$mdp)) {
			echo 'Good mdp';
		} else {
			echo 'Bad mdp';
		}
	}*/

	$code = '
	ZEROONEZEROZEROZEROZEROONEZERO ZEROONEONEZEROONEONEONEONE ZEROONEONEZEROONEONEONEZERO ZEROONEONEZEROONEZEROONEZERO ZEROONEONEZEROONEONEONEONE ZEROONEONEONEZEROONEZEROONE ZEROONEONEONEZEROZEROONEZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEZEROZEROZEROONEZEROZERO ZEROONEONEZEROZEROONEZEROONE ZEROONEONEZEROONEONEONEONE ZEROONEONEZEROZEROONEZEROONE ZEROONEONEZEROONEONEZEROZERO ZEROZEROONEZEROONEONEZEROZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROZEROZEROZEROONEONEZEROONE ZEROZEROZEROZEROONEZEROONEZERO ZEROONEZEROONEZEROZEROONEONE ZEROONEONEZEROONEZEROZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEONEZEROONEZEROZERO ZEROONEONEONEZEROONEZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROZEROZEROONE ZEROONEONEONEZEROZEROONEZERO ZEROONEONEONEZEROZEROONEZERO ZEROONEONEZEROONEZEROZEROONE ZEROONEONEONEZEROONEONEZERO ZEROONEONEZEROZEROONEZEROONE ZEROONEONEONEZEROZEROONEONE ZEROZEROONEZEROZEROZEROZEROZERO ONEONEZEROZEROZEROZEROONEONE ONEZEROONEZEROZEROZEROZEROZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROONEONEZEROZERO ZEROONEONEZEROONEZEROZEROONE ZEROONEONEONEZEROZEROONEZERO ZEROONEONEZEROZEROONEZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROZEROONEONE ZEROONEONEZEROZEROONEZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROONEONEZEROONE ZEROONEONEZEROZEROONEZEROONE ZEROONEONEONEZEROZEROONEONE ZEROONEONEONEZEROZEROONEONE ZEROONEONEZEROZEROZEROZEROONE ZEROONEONEZEROZEROONEONEONE ZEROONEONEZEROZEROONEZEROONE ZEROZEROONEZEROONEONEZEROZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROZEROONEONE ZEROONEONEZEROZEROONEZEROONE ZEROONEONEZEROONEONEZEROZERO ZEROONEONEZEROZEROZEROZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEONEZEROONEONEZERO ZEROONEONEZEROZEROONEZEROONE ZEROONEONEONEZEROONEZEROONE ZEROONEONEONEONEZEROZEROZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROONEZEROZERO ZEROONEONEZEROONEZEROZEROONE ZEROONEONEONEZEROZEROONEZERO ZEROONEONEZEROZEROONEZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEONEZEROZEROZEROONE ZEROONEONEONEZEROONEZEROONE ZEROONEONEZEROZEROONEZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEONEZEROONEZEROZERO ZEROONEONEONEZEROONEZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROZEROZEROONE ZEROONEONEONEZEROZEROONEONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROONEZEROONE ZEROONEONEZEROONEONEONEZERO ZEROONEONEZEROZEROONEONEZERO ZEROONEONEZEROONEZEROZEROONE ZEROONEONEZEROONEONEONEZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROZEROONEONE ZEROONEONEZEROONEONEONEONE ZEROONEONEZEROONEONEZEROONE ZEROONEONEONEZEROZEROZEROZERO ZEROONEONEONEZEROZEROONEZERO ZEROONEONEZEROONEZEROZEROONE ZEROONEONEONEZEROZEROONEONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROZEROONEONE ZEROONEONEZEROONEONEONEONE ZEROONEONEZEROONEONEZEROONE ZEROONEONEZEROONEONEZEROONE ZEROONEONEZEROZEROONEZEROONE ZEROONEONEZEROONEONEONEZERO ZEROONEONEONEZEROONEZEROZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROONEZEROZERO ONEONEZEROZEROZEROZEROONEONE ONEZEROONEZEROONEZEROZEROONE ZEROONEONEZEROZEROZEROONEONE ZEROONEONEZEROONEONEONEONE ZEROONEONEZEROZEROONEZEROZERO ZEROONEONEZEROZEROONEZEROONE ZEROONEONEONEZEROZEROONEZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROZEROONEONE ZEROONEONEZEROZEROONEZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEONEZEROONEZEROZERO ZEROONEONEONEZEROZEROONEZERO ZEROONEONEONEZEROONEZEROONE ZEROONEONEZEROZEROZEROONEONE ZEROZEROONEZEROONEONEONEZERO ZEROZEROZEROZEROONEONEZEROONE ZEROZEROZEROZEROONEZEROONEZERO ZEROONEZEROZEROZEROZEROONEONE ZEROZEROONEZEROZEROONEONEONE ZEROONEONEZEROZEROONEZEROONE ZEROONEONEONEZEROZEROONEONE ZEROONEONEONEZEROONEZEROZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEONEZEROONEONEZERO ZEROONEONEONEZEROZEROONEZERO ZEROONEONEZEROZEROZEROZEROONE ZEROONEONEZEROONEZEROZEROONE ZEROONEONEZEROONEONEZEROONE ZEROONEONEZEROZEROONEZEROONE ZEROONEONEZEROONEONEONEZERO ZEROONEONEONEZEROONEZEROZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEONEZEROONEZEROZERO ZEROONEONEONEZEROZEROONEZERO ONEONEZEROZEROZEROZEROONEONE ONEZEROONEZEROONEZEROZEROZERO ZEROONEONEONEZEROZEROONEONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEONEZEROZEROONEONE ZEROONEONEZEROONEZEROZEROONE ZEROONEONEZEROONEONEZEROONE ZEROONEONEONEZEROZEROZEROZERO ZEROONEONEZEROONEONEZEROZERO ZEROONEONEZEROZEROONEZEROONE ZEROZEROONEZEROONEONEONEZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROZEROZEROZEROONEONEZEROONE ZEROZEROZEROZEROONEZEROONEZERO ZEROONEZEROONEZEROONEONEZERO ZEROONEONEZEROONEONEONEONE ZEROONEONEZEROONEZEROZEROONE ZEROONEONEZEROZEROZEROONEONE ZEROONEONEZEROONEZEROZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROONEONEZEROZERO ZEROONEONEZEROZEROONEZEROONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEONEZEROZEROONEONEZERO ZEROONEONEZEROONEONEZEROZERO ZEROONEONEZEROZEROZEROZEROONE ZEROONEONEZEROZEROONEONEONE ZEROZEROONEZEROZEROZEROZEROZERO ZEROZEROONEONEONEZEROONEZERO ZEROZEROONEZEROZEROZEROZEROZERO ZEROONEZEROZEROZEROONEONEZERO ZEROONEZEROZEROONEONEZEROZERO ZEROONEZEROZEROZEROZEROZEROONE ZEROONEZEROZEROZEROONEONEONE ZEROONEONEONEONEZEROONEONE ZEROONEZEROZEROONEZEROONEZERO ZEROZEROONEONEZEROZEROONEONE ZEROONEZEROONEONEONEONEONE ZEROONEONEONEZEROONEZEROZERO ZEROZEROONEZEROZEROONEONEONE ZEROONEONEZEROZEROZEROZEROONE ZEROONEONEZEROONEZEROZEROONE ZEROONEONEZEROONEONEZEROONE ZEROZEROONEONEZEROZEROONEONE ZEROONEZEROONEONEONEONEONE ZEROONEONEZEROZEROZEROONEZERO ZEROONEONEZEROONEZEROZEROONE ZEROZEROONEONEZEROZEROONEONE ZEROONEONEZEROONEONEONEZERO ZEROONEZEROONEONEONEONEONE ZEROONEONEZEROZEROONEONEZERO ZEROONEONEONEZEROZEROONEZERO ZEROZEROONEONEZEROZEROONEONE ZEROONEONEONEZEROZEROONEZERO ZEROZEROONEONEZEROZEROONEONE ZEROONEONEONEONEONEZERO
	';
	$code = str_replace('ZERO','0',$code);
	$code = str_replace('ONE','1',$code);
	echo $code;
?>
